Custom theme
bench-routes/dashboard pull request #1
Opened 2021-06-06 12:46 UTC by ruddi10

2021-06-06 13:08 UTC, ruddi10 commented
@muskankhedia  @aquibbaig PTAL

2021-06-07 06:08 UTC, aquibbaig commented
@ruddi10 For initials, please run a `yarn format` and then fix the following warnings:
```
src/layouts/BasicLayout.tsx
  Line 2:27:  'useState' is defined but never used  @typescript-eslint/no-unused-vars

src/theme/global.tsx
  Line 4:13:  Missing return type on function                       @typescript-eslint/explicit-module-boundary-types
  Line 4:14:  Argument 'props' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types
  Line 4:21:  Unexpected any. Specify a different type              @typescript-eslint/no-explicit-any
```

2021-06-07 06:47 UTC, ruddi10 commented
> @ruddi10 For initials, please run a `yarn format` and then fix the following warnings:
> 
> ```
> src/layouts/BasicLayout.tsx
>   Line 2:27:  'useState' is defined but never used  @typescript-eslint/no-unused-vars
> 
> src/theme/global.tsx
>   Line 4:13:  Missing return type on function                       @typescript-eslint/explicit-module-boundary-types
>   Line 4:14:  Argument 'props' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types
>   Line 4:21:  Unexpected any. Specify a different type              @typescript-eslint/no-explicit-any
> ```

Have fixed this

2021-06-08 06:37 UTC, aquibbaig requested changes
The files inside `theme` directory can be simple typescript files since they do not include any JSX

2021-06-08 06:39 UTC, aquibbaig requested changes

2021-06-08 06:39 UTC, aquibbaig commented on src/theme/branding.tsx
> +    darkSecondary: "#121212",
Separate background variables from text variables using consistent naming

2021-06-12 17:25 UTC, muskankhedia approved these changes
LGTM!

2021-06-13 10:32 UTC, merged