fetch button centered
bench-routes/dashboard pull request #33
Opened 2021-10-17 11:47 UTC by satyaarthchhabra

hi in this pull request i have tried to resolve this  [issue ](https://github.com/bench-routes/dashboard/issues/31). 

description:
i have just aligned the items both vertically and horizontally

2021-10-17 12:35 UTC, ruddi10 commented
@satyaarthchhabra Its a good practice of adding proof of what you have achieved while making the PR, A small video or gif will be good for eg- use Peek

2021-10-21 06:40 UTC, aquibbaig requested changes

2021-10-21 06:40 UTC, aquibbaig commented on src/components/TimeQuerier/index.tsx
> +        alignItems="center"
I think we are better off with a `textAlign: center` property. A flexbox with one child (Button) does not make sense to me

2021-11-14 14:12 UTC, aquibbaig commented
@satyaarthchhabra any updates yet?

2021-11-17 20:13 UTC, rijusougata13 commented
hi @aquibbaig  can I go with this issue if no one working on it?

2021-11-18 06:00 UTC, aquibbaig commented
@rijusougata13 I think we should move ahead. This PR is like 28days old and doesn't have any updates. Please create a new PR with the changes. I'm closing this for now, we'll reopen it if the author comes back to it

2021-11-18 06:00 UTC, closed without merging