responsive view in mobile devices
bench-routes/dashboard pull request #41
Opened 2021-11-18 22:04 UTC by rijusougata13

previous mobile view :
![Screenshot (23)](https://user-images.githubusercontent.com/52108435/142503984-1438e246-ad6f-4b7c-b484-f963d55dc4c0.png)
 current mobile view:
![Screenshot (21)](https://user-images.githubusercontent.com/52108435/142504060-0da28c28-385e-43b0-8f37-2a04c209a907.png)
current desktop view:

![Screenshot (20)](https://user-images.githubusercontent.com/52108435/142504086-1e07528b-0ba6-4910-8789-16f609ce13d9.png)

I have used chakra ui flex to make them responsive

2021-11-18 22:06 UTC, rijusougata13 commented
PTAL @aquibbaig  @ruddi10

2021-11-19 05:19 UTC, ruddi10 commented
> PTAL @aquibbaig @ruddi10

@rijusougata13 I think our project is meant for pcs desktops and laptops so it wasn't required to make the screen responsive for mobiles. @aquibbaig what do you think

2021-11-19 07:28 UTC, aquibbaig commented
makes sense but I wont discard this change, this certainly is a "good to have".

2021-11-19 09:13 UTC, rijusougata13 commented
got the point that it's only desktop only so don't need to optimize it for mobile. But still we have to present the dashboard to user such that they can at least use our dashboard on mobile also. So I proposed this small change and Ig we can merge it to the main repo.

2021-11-19 10:02 UTC, ruddi10 commented
@rijusougata13 yes I also feel we can merge this it's a small change that's good to have 😁

2021-11-19 10:04 UTC, ruddi10 commented
Hey @rijusougata13 in the ss you have shared I can see white space on the top of bench routes logo please have a look at that, it shouldn't be the case

2021-11-19 10:11 UTC, rijusougata13 commented
> Hey @rijusougata13 in the ss you have shared I can see white space on the top of bench routes logo please have a look at that, it shouldn't be the case

okay!! on it.

2021-11-19 18:13 UTC, ruddi10 requested changes

2021-12-12 20:29 UTC, rijusougata13 commented on src/pages/Home/index.tsx
> +    </Flex>
Fixed this. PTAL @ruddi10.

2022-01-10 05:41 UTC, aquibbaig commented
cc: @ruddi10

2022-01-12 12:35 UTC, ruddi10 commented
@rijusougata13 you have given Flex props to the Grid I don't think it should work, also even if it's working I don't think it's a good practice.

2022-01-12 13:59 UTC, rijusougata13 commented
sure @ruddi10  I'll send a fix within tonight removing that

2022-01-12 19:47 UTC, rijusougata13 commented
Hi removed  the flex @ruddi10. I think its good to go now.

2022-01-16 18:17 UTC, aquibbaig approved these changes

2022-01-16 19:57 UTC, ruddi10 commented
Hey @rijusougata13 can you just share the screenshot of new desktop and mobile view after these changes then we are good to go

2022-01-16 21:40 UTC, rijusougata13 commented
![image](https://user-images.githubusercontent.com/52108435/149679173-089b7018-ec32-4d0a-a1a9-eb2c1a5895ab.png)
![image](https://user-images.githubusercontent.com/52108435/149679182-cab26556-6498-417d-b698-41fe81740ee7.png)

2022-01-16 21:43 UTC, rijusougata13 commented
@ruddi10

2022-01-17 06:41 UTC, ruddi10 commented
> @ruddi10 
> 

Hey the height of the error message box on the right don't seem right, and is different from older height. Maybe making the height of the Box 100 vh might solve the problem.

2022-01-17 06:42 UTC, ruddi10 commented
Also use 100% instead of vh in the Box heights

2022-01-17 20:29 UTC, rijusougata13 commented
> Also use 100% instead of vh in the Box heights

yep but I have to set the parent height to 100vh to acquire hole height of the page

2022-01-18 06:07 UTC, ruddi10 commented
@rijusougata13 the desktop view looks fine now can you just share the ss of mobile view once then we are good to go if it looks fine

2022-01-29 12:27 UTC, muskankhedia approved these changes
LGTM!

Suggestion for future: On mobile view, we could show the chart below the filters. A demo design could be:

![image](https://user-images.githubusercontent.com/36980003/151660978-8b52b8ca-4433-4470-b1bd-c0fbf7b1ab3f.png)

@aquibbaig @ruddi10 @rijusougata13  Please share your thoughts on this.

2022-01-30 14:34 UTC, ruddi10 approved these changes

2022-01-30 14:55 UTC, merged