made data pattern consistent across all the page components wrt useFetch
bench-routes/dashboard pull request #42
Opened 2021-12-08 13:53 UTC by akshatgarg12

2021-12-09 08:19 UTC, aquibbaig commented
Let me know when this is ready for a review

2021-12-09 15:57 UTC, akshatgarg12 commented
> Let me know when this is ready for a review

Ready from my side

2021-12-27 09:37 UTC, aquibbaig reviewed
You are not adding any dependency, so do not make changes to package.json

2021-12-27 09:43 UTC, aquibbaig requested changes
Thanks for the PR and sorry for the late review, I've added some comments. These changes more or less look great, some small changes and we're good to go

2021-12-27 09:43 UTC, aquibbaig commented on src/components/GraphWrapper/graphWrapper.test.tsx
> +const { defaultStartTimestamp, defaultStepValue, defaultEndTimestamp } =
shouldn't be a part of the changes, please enable prettier on your system to auto save formattings

2021-12-27 09:43 UTC, aquibbaig commented on src/components/GraphWrapper/index.tsx
> +  const { selectedStartTimestamp, selectedEndTimestamp, selectedStepValue } =
shouldn't be a part of the changes

2021-12-27 09:43 UTC, aquibbaig commented on src/components/MachineSelector/index.tsx
> +import {
these formatting changes look good 👍

2021-12-27 09:43 UTC, aquibbaig commented on src/components/TimeQuerier/index.tsx
> +  const { selectedStartTimestamp, selectedEndTimestamp, changeTimeQuerier } =
the older changes were fine

2021-12-27 09:43 UTC, aquibbaig commented on src/theme/components/DateTime.ts
> +    ,td.rdtMonth:hover, td.rdtYear:hover,.rdtSwitch:hover":
revert

2021-12-27 09:43 UTC, aquibbaig commented on src/utils/useFetch.ts
> +          // @ts-ignore
why was this change introduced here?

2021-12-28 15:59 UTC, akshatgarg12 commented on src/utils/useFetch.ts
> +          // @ts-ignore
this is not required , I'll remove this

2021-12-28 16:01 UTC, akshatgarg12 commented
@aquibbaig all of the formatting changes are introduced while commiting the code, as it runs yarn prettier -fix, how should i revert these changes?

2021-12-31 11:16 UTC, aquibbaig commented on src/utils/useFetch.ts
> +          // @ts-ignore
Please do

2021-12-31 11:19 UTC, aquibbaig commented
> @aquibbaig all of the formatting changes are introduced while commiting the code, as it runs yarn prettier -fix, how should i revert these changes?

If it is a part of basic `git commit`  workflow, then lets not change that, we will redefine these rules as a part of a new prettier configuration

2022-01-02 13:43 UTC, akshatgarg12 commented on src/utils/useFetch.ts
> +          // @ts-ignore
done

2022-01-10 05:25 UTC, aquibbaig approved these changes

2022-01-10 05:25 UTC, merged