remove any from catch error block
bench-routes/dashboard pull request #45
Opened 2022-01-12 21:02 UTC by rijusougata13

Hi,  In TypeScript, catch clause variables may not have a type annotation (aside from, as of TypeScript 4.0, unknown).It doesn't allow type annotations on catch clauses because there's really no way to know what type an exception will have. You can throw objects of any type and system generated exceptions (such as out of memory exception) can technically happen at any time.

So removed Any annotation from try catch block also its giving the error.

2022-01-12 21:03 UTC, rijusougata13 commented
![Screenshot (38)](https://user-images.githubusercontent.com/52108435/149221122-782d84dd-a412-4d69-86cf-7c547d0a7e27.png)

@aquibbaig  @ruddi10  PTAL

2022-01-12 21:33 UTC, aquibbaig requested changes
don't add dependencies and lockfile, were good to go otherwise

2022-01-13 06:50 UTC, rijusougata13 commented
Hi @aquibbaig  should I add those files in gitignore, as for future git will not track those file if someone going to push

2022-01-13 07:40 UTC, aquibbaig commented
just check out those files for now

2022-01-16 08:09 UTC, rijusougata13 commented
> just check out those files for now

Hi @aquibbaig  removed those file

2022-01-16 18:15 UTC, aquibbaig approved these changes

2022-01-16 18:15 UTC, merged